#!/bin/bash

# List explicitly installed pacman packages in a text file w/"current" symlink

set -euo pipefail

OUTPUT_DIR="$HOME/documents/archive/003_Program Files"

mkdir -p "$OUTPUT_DIR"

FILE="$OUTPUT_DIR/package-list-$(date +%F).txt"

pacman -Qeq > "$FILE"

ln -sfn "$FILE" "$OUTPUT_DIR/package-list-current.txt"

echo "Package list saved to $FILE"
